// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository_Pattern.Data;

#nullable disable

namespace Repository_Pattern.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124182225_fulldbsetup")]
    partial class fulldbsetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository_Pattern.Models.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("departmaneDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departmanetName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("id");

                    b.ToTable("Department", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            departmaneDesc = "Esc Departmetn",
                            departmanetName = "ESC"
                        },
                        new
                        {
                            id = 2,
                            departmaneDesc = "CSE Departmetn",
                            departmanetName = "CSE"
                        });
                });

            modelBuilder.Entity("Repository_Pattern.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("Repository_Pattern.Models.student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DepratmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DepratmentId");

                    b.ToTable("student", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "43243243432",
                            Email = "rohit@gmail.com",
                            Name = "Rohit",
                            Phone = "4324324234",
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ambala",
                            Email = "Mohit@gmail.com",
                            Name = "Mohit",
                            Phone = "23424324324",
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bilaspur",
                            Email = "Rajat@gmail.com",
                            Name = "Rajat",
                            Phone = "345345345",
                            Status = false
                        });
                });

            modelBuilder.Entity("Repository_Pattern.Models.student", b =>
                {
                    b.HasOne("Repository_Pattern.Models.Department", "Department")
                        .WithMany("students")
                        .HasForeignKey("DepratmentId")
                        .HasConstraintName("Fk_student_Department");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Repository_Pattern.Models.Department", b =>
                {
                    b.Navigation("students");
                });
#pragma warning restore 612, 618
        }
    }
}
